changed button, fixed load issues with profile pictures
assistancechat/assistance.chat pull request #90
Opened 2023-02-18 16:48 UTC by Kennie12345

2023-02-19 05:47 UTC, SimonBiggs requested changes
@Kennie12345, there's a package issue. See comment.

2023-02-19 05:47 UTC, SimonBiggs commented on examples/student.assistance.chat/package.json
> +    "@next/swc-darwin-x64": "^13.1.6",
@Kennie12345 this package makes it so that it can't build on the server...

2023-02-20 01:53 UTC, Kennie12345 reviewed
fix for package issue

2023-02-26 21:23 UTC, SimonBiggs commented
@Kennie12345, I'm going to close this PR.

Feel free to re-submit it if you'd like these changes merged.

2023-02-26 21:23 UTC, closed without merging

2023-02-26 23:00 UTC, Kennie12345 commented
Thanks bro!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Simon Biggs ***@***.***>
Sent: Monday, February 27, 2023 6:23:56 AM
To: assistancechat/assistance.chat ***@***.***>
Cc: Kennie12345 ***@***.***>; Mention ***@***.***>
Subject: Re: [assistancechat/assistance.chat] changed button, fixed load issues with profile pictures (PR #90)


@Kennie12345<https://github.com/Kennie12345>, I'm going to close this PR.

Feel free to re-submit it if you'd like these changes merged.

—
Reply to this email directly, view it on GitHub<https://github.com/assistancechat/assistance.chat/pull/90#issuecomment-1445471145>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMUIHHZYV2GNMUNOBT5KQKLWZPCWZANCNFSM6AAAAAAVAOFR4Q>.
You are receiving this because you were mentioned.Message ID: ***@***.***>